/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import connection.Communication;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author Folio1040
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setLocationRelativeTo(this);
        try {
            Communication.getInstance();
            lblKonekcija.setText("Uspesno ste povezani na server!");
        } catch (Exception ex) {
            ex.printStackTrace();
            lblKonekcija.setText("Niste povezani na server. Doslo je do greske. "+ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        lblKonekcija = new javax.swing.JLabel();
        lblPozadina = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiKreirajClana = new javax.swing.JMenuItem();
        jmiPrikaziSve = new javax.swing.JMenuItem();
        jmiStatistike = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiKreirajTakmicenje = new javax.swing.JMenuItem();
        jmiKreirajTakmicara = new javax.swing.JMenuItem();
        jmiRezultatTakmicenja = new javax.swing.JMenuItem();
        jmiPrikaziTakmicare = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jmiKreirajPolaganje = new javax.swing.JMenuItem();
        jmiRezultatPolaganja = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jmiKreirajTim = new javax.swing.JMenuItem();
        jmiPogledajSveTimove = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblKonekcija.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblKonekcija.setForeground(new java.awt.Color(20, 34, 89));
        lblKonekcija.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblPozadina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKonekcija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(lblPozadina, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(201, 201, 201))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblPozadina, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblKonekcija, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        jMenuBar1.setBackground(new java.awt.Color(20, 34, 89));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(258, 40));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Clan");

        jmiKreirajClana.setBackground(new java.awt.Color(20, 34, 89));
        jmiKreirajClana.setForeground(new java.awt.Color(255, 255, 255));
        jmiKreirajClana.setText("Kreiraj");
        jMenu1.add(jmiKreirajClana);

        jmiPrikaziSve.setBackground(new java.awt.Color(20, 34, 89));
        jmiPrikaziSve.setForeground(new java.awt.Color(255, 255, 255));
        jmiPrikaziSve.setText("Prikazi sve");
        jMenu1.add(jmiPrikaziSve);

        jmiStatistike.setBackground(new java.awt.Color(20, 34, 89));
        jmiStatistike.setForeground(new java.awt.Color(255, 255, 255));
        jmiStatistike.setText("Statistike clanova");
        jMenu1.add(jmiStatistike);

        jMenuBar1.add(jMenu1);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Takmicenje");

        jmiKreirajTakmicenje.setBackground(new java.awt.Color(20, 34, 89));
        jmiKreirajTakmicenje.setForeground(new java.awt.Color(255, 255, 255));
        jmiKreirajTakmicenje.setText("Kreiraj takmicenje");
        jMenu4.add(jmiKreirajTakmicenje);

        jmiKreirajTakmicara.setBackground(new java.awt.Color(20, 34, 89));
        jmiKreirajTakmicara.setForeground(new java.awt.Color(255, 255, 255));
        jmiKreirajTakmicara.setText("Kreiraj takmicara");
        jMenu4.add(jmiKreirajTakmicara);

        jmiRezultatTakmicenja.setBackground(new java.awt.Color(20, 34, 89));
        jmiRezultatTakmicenja.setForeground(new java.awt.Color(255, 255, 255));
        jmiRezultatTakmicenja.setText("Unesi rezultate takmicenja");
        jMenu4.add(jmiRezultatTakmicenja);

        jmiPrikaziTakmicare.setBackground(new java.awt.Color(20, 34, 89));
        jmiPrikaziTakmicare.setForeground(new java.awt.Color(255, 255, 255));
        jmiPrikaziTakmicare.setText("Prikazi sve takmicare");
        jMenu4.add(jmiPrikaziTakmicare);

        jMenuBar1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setText("Polaganje");

        jmiKreirajPolaganje.setBackground(new java.awt.Color(20, 34, 89));
        jmiKreirajPolaganje.setForeground(new java.awt.Color(255, 255, 255));
        jmiKreirajPolaganje.setText("Kreiraj polaganje");
        jMenu5.add(jmiKreirajPolaganje);

        jmiRezultatPolaganja.setBackground(new java.awt.Color(20, 34, 89));
        jmiRezultatPolaganja.setForeground(new java.awt.Color(255, 255, 255));
        jmiRezultatPolaganja.setText("Dodaj rezultate polaganja");
        jMenu5.add(jmiRezultatPolaganja);

        jMenuBar1.add(jMenu5);

        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setText("Timovi");

        jmiKreirajTim.setBackground(new java.awt.Color(20, 34, 89));
        jmiKreirajTim.setForeground(new java.awt.Color(255, 255, 255));
        jmiKreirajTim.setText("Kreiraj tim");
        jMenu6.add(jmiKreirajTim);

        jmiPogledajSveTimove.setBackground(new java.awt.Color(20, 34, 89));
        jmiPogledajSveTimove.setForeground(new java.awt.Color(255, 255, 255));
        jmiPogledajSveTimove.setText("Pogledaj sve timove");
        jMenu6.add(jmiPogledajSveTimove);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jmiKreirajClana;
    private javax.swing.JMenuItem jmiKreirajPolaganje;
    private javax.swing.JMenuItem jmiKreirajTakmicara;
    private javax.swing.JMenuItem jmiKreirajTakmicenje;
    private javax.swing.JMenuItem jmiKreirajTim;
    private javax.swing.JMenuItem jmiPogledajSveTimove;
    private javax.swing.JMenuItem jmiPrikaziSve;
    private javax.swing.JMenuItem jmiPrikaziTakmicare;
    private javax.swing.JMenuItem jmiRezultatPolaganja;
    private javax.swing.JMenuItem jmiRezultatTakmicenja;
    private javax.swing.JMenuItem jmiStatistike;
    private javax.swing.JLabel lblKonekcija;
    private javax.swing.JLabel lblPozadina;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getJmiKreirajClana() {
        return jmiKreirajClana;
    }

    public JMenuItem getJmiPrikaziSve() {
        return jmiPrikaziSve;
    }

    public JMenuItem getJmiKreirajTim() {
        return jmiKreirajTim;
    }

    public JMenuItem getJmiKreirajTakmicara() {
        return jmiKreirajTakmicara;
    }

    public JMenuItem getJmiPogledajSveTimove() {
        return jmiPogledajSveTimove;
    }

    public JMenuItem getJmiKreirajPolaganje() {
        return jmiKreirajPolaganje;
    }

    public JMenuItem getJmiKreirajTakmicenje() {
        return jmiKreirajTakmicenje;
    }

    public JMenuItem getJmiRezultatPolaganja() {
        return jmiRezultatPolaganja;
    }

    public JMenuItem getJmiRezultatTakmicenja() {
        return jmiRezultatTakmicenja;
    }

    public JMenuItem getJmiStatistike() {
        return jmiStatistike;
    }

    public JLabel getLblPozadina() {
        return lblPozadina;
    }

    public JMenuItem getJmiPrikaziTakmicare() {
        return jmiPrikaziTakmicare;
    }
    
    
}
