/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Folio1040
 */
public class FrmRezultatTakmicenja extends javax.swing.JDialog {

    /**
     * Creates new form FrmRezultatTakmicenja
     */
    public FrmRezultatTakmicenja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbTakmicari = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbTakmicenja = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtPlasman = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPoeni = new javax.swing.JTextField();
        btnZapamtiIzbor = new javax.swing.JButton();
        panelTim = new javax.swing.JPanel();
        lblTim = new javax.swing.JLabel();
        lblPojedinacno = new javax.swing.JLabel();
        chbTim = new javax.swing.JCheckBox();
        chbPojedinacno = new javax.swing.JCheckBox();
        btnUnesi = new javax.swing.JButton();
        lblSlika = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezultati = new javax.swing.JTable();
        btnZapamtiRezultat = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 236, 248));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(39, 45, 87));
        jLabel1.setText("Izaberite takmicara:");

        cbTakmicari.setBackground(new java.awt.Color(232, 242, 250));
        cbTakmicari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTakmicari.setForeground(new java.awt.Color(39, 45, 87));
        cbTakmicari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 45, 87));
        jLabel2.setText("Izaberite takmicenje:");

        cbTakmicenja.setBackground(new java.awt.Color(232, 242, 250));
        cbTakmicenja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTakmicenja.setForeground(new java.awt.Color(39, 45, 87));
        cbTakmicenja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 45, 87));
        jLabel3.setText("Unesite plasman:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(39, 45, 87));
        jLabel4.setText("Unesite poene:");

        btnZapamtiIzbor.setBackground(new java.awt.Color(39, 45, 87));
        btnZapamtiIzbor.setForeground(new java.awt.Color(255, 255, 255));
        btnZapamtiIzbor.setText("Zapamti izbor");

        panelTim.setBackground(new java.awt.Color(232, 242, 250));
        panelTim.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Podaci o takmicaru", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14))); // NOI18N
        panelTim.setForeground(new java.awt.Color(39, 45, 87));

        lblTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTim.setForeground(new java.awt.Color(39, 45, 87));
        lblTim.setText("Takimicar se takmici u timu");

        lblPojedinacno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPojedinacno.setForeground(new java.awt.Color(39, 45, 87));
        lblPojedinacno.setText("Takmicar se takmici pojedinacno");

        chbTim.setBackground(new java.awt.Color(232, 242, 250));
        chbTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbTim.setForeground(new java.awt.Color(39, 45, 87));
        chbTim.setText("Izaberi takmicenje u timu");

        chbPojedinacno.setBackground(new java.awt.Color(232, 242, 250));
        chbPojedinacno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbPojedinacno.setForeground(new java.awt.Color(39, 45, 87));
        chbPojedinacno.setText("Izaberi pojedinacno takmicenje");

        javax.swing.GroupLayout panelTimLayout = new javax.swing.GroupLayout(panelTim);
        panelTim.setLayout(panelTimLayout);
        panelTimLayout.setHorizontalGroup(
            panelTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTim)
                    .addComponent(lblPojedinacno))
                .addGap(18, 18, 18)
                .addGroup(panelTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbPojedinacno)
                    .addComponent(chbTim))
                .addGap(50, 50, 50))
        );
        panelTimLayout.setVerticalGroup(
            panelTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTim)
                    .addComponent(chbTim))
                .addGap(18, 18, 18)
                .addGroup(panelTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPojedinacno)
                    .addComponent(chbPojedinacno))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnUnesi.setBackground(new java.awt.Color(39, 45, 87));
        btnUnesi.setForeground(new java.awt.Color(255, 255, 255));
        btnUnesi.setText("Unesi rezultat");

        tblRezultati.setBackground(new java.awt.Color(232, 242, 250));
        tblRezultati.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblRezultati.setForeground(new java.awt.Color(39, 45, 87));
        tblRezultati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRezultati.setGridColor(new java.awt.Color(39, 45, 87));
        jScrollPane1.setViewportView(tblRezultati);

        btnZapamtiRezultat.setBackground(new java.awt.Color(39, 45, 87));
        btnZapamtiRezultat.setForeground(new java.awt.Color(255, 255, 255));
        btnZapamtiRezultat.setText("Zapamti rezultat");

        btnObrisi.setBackground(new java.awt.Color(255, 102, 102));
        btnObrisi.setForeground(new java.awt.Color(255, 255, 255));
        btnObrisi.setText("Obrisi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelTim, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPlasman, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTakmicenja, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPoeni)
                                    .addComponent(cbTakmicari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnZapamtiRezultat)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnZapamtiIzbor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTakmicari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZapamtiIzbor)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(panelTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTakmicenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlasman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPoeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesi)
                    .addComponent(btnObrisi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnZapamtiRezultat)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRezultatTakmicenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRezultatTakmicenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRezultatTakmicenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRezultatTakmicenja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRezultatTakmicenja dialog = new FrmRezultatTakmicenja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JButton btnZapamtiIzbor;
    private javax.swing.JButton btnZapamtiRezultat;
    private javax.swing.JComboBox cbTakmicari;
    private javax.swing.JComboBox cbTakmicenja;
    private javax.swing.JCheckBox chbPojedinacno;
    private javax.swing.JCheckBox chbTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPojedinacno;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JLabel lblTim;
    private javax.swing.JPanel panelTim;
    private javax.swing.JTable tblRezultati;
    private javax.swing.JTextField txtPlasman;
    private javax.swing.JTextField txtPoeni;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnZapamtiIzbor() {
        return btnZapamtiIzbor;
    }

    public JButton getBtnZapamtiRezultat() {
        return btnUnesi;
    }

    public JComboBox getCbTakmicari() {
        return cbTakmicari;
    }

    public JComboBox getCbTakmicenja() {
        return cbTakmicenja;
    }

    public JCheckBox getChbPojedinacno() {
        return chbPojedinacno;
    }

    public JCheckBox getChbTim() {
        return chbTim;
    }

    public JPanel getPanelTim() {
        return panelTim;
    }

    public JTextField getTxtPlasman() {
        return txtPlasman;
    }

    public JTextField getTxtPoeni() {
        return txtPoeni;
    }

    public void addZapamtiIzborListener(ActionListener actionListener) {
        btnZapamtiIzbor.addActionListener(actionListener);
    }

    public JLabel getLblPojedinacno() {
        return lblPojedinacno;
    }

    public JLabel getLblTim() {
        return lblTim;
    }

    public void addZapamtiRezultat(ActionListener actionListener) {
        btnZapamtiRezultat.addActionListener(actionListener);
    }

    public JLabel getLblSlika() {
        return lblSlika;
    }

    public JButton getBtnUnesi() {
        return btnUnesi;
    }

    public void addUnesiListener(ActionListener actionListener) {
        btnUnesi.addActionListener(actionListener);
    }

    public JTable getTblRezultati() {
        return tblRezultati;
    }

    public void addObrisiListener(ActionListener actionListener) {
        btnObrisi.addActionListener(actionListener);
    }
    
    

}
