/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import cordinator.MainCordinator;
import domen.Tim;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Folio1040
 */
public class FrmTim extends javax.swing.JDialog {

    /**
     * Creates new form FrmTim
     */
    public FrmTim(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelPostojeciTim = new javax.swing.JPanel();
        cbTimovi = new javax.swing.JComboBox();
        btnZapamtiIzbor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTimID = new javax.swing.JTextField();
        chbTimBorbe = new javax.swing.JCheckBox();
        chbTimKate = new javax.swing.JCheckBox();
        chbTakmicarskiTim = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtNazivTima = new javax.swing.JTextField();
        btnZapamti = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisiTim = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 236, 248));

        panelPostojeciTim.setBackground(new java.awt.Color(232, 242, 250));
        panelPostojeciTim.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Postojeci tim"), "Postojeci tim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(39, 45, 87))); // NOI18N
        panelPostojeciTim.setForeground(new java.awt.Color(39, 45, 87));

        cbTimovi.setBackground(new java.awt.Color(39, 45, 87));
        cbTimovi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTimovi.setForeground(new java.awt.Color(255, 255, 255));
        cbTimovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTimovi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTimoviItemStateChanged(evt);
            }
        });

        btnZapamtiIzbor.setBackground(new java.awt.Color(39, 45, 87));
        btnZapamtiIzbor.setForeground(new java.awt.Color(255, 255, 255));
        btnZapamtiIzbor.setText("Zapamti izbor");

        javax.swing.GroupLayout panelPostojeciTimLayout = new javax.swing.GroupLayout(panelPostojeciTim);
        panelPostojeciTim.setLayout(panelPostojeciTimLayout);
        panelPostojeciTimLayout.setHorizontalGroup(
            panelPostojeciTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPostojeciTimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPostojeciTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTimovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPostojeciTimLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnZapamtiIzbor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPostojeciTimLayout.setVerticalGroup(
            panelPostojeciTimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPostojeciTimLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTimovi)
                .addGap(18, 18, 18)
                .addComponent(btnZapamtiIzbor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(232, 242, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novi tim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(39, 45, 87))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(39, 45, 87));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 45, 87));
        jLabel6.setText("Tim id:");

        txtTimID.setEnabled(false);

        chbTimBorbe.setBackground(new java.awt.Color(232, 242, 250));
        chbTimBorbe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbTimBorbe.setForeground(new java.awt.Color(39, 45, 87));
        chbTimBorbe.setText("Tim za borbe:");

        chbTimKate.setBackground(new java.awt.Color(232, 242, 250));
        chbTimKate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbTimKate.setForeground(new java.awt.Color(39, 45, 87));
        chbTimKate.setText("Tim za kate:");

        chbTakmicarskiTim.setBackground(new java.awt.Color(232, 242, 250));
        chbTakmicarskiTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbTakmicarskiTim.setForeground(new java.awt.Color(39, 45, 87));
        chbTakmicarskiTim.setText("Takmicarski tim");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(39, 45, 87));
        jLabel1.setText("Naziv tima:");

        btnZapamti.setBackground(new java.awt.Color(39, 45, 87));
        btnZapamti.setForeground(new java.awt.Color(255, 255, 255));
        btnZapamti.setText("Kreiraj novi tim");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNazivTima))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbTakmicarskiTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chbTimKate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTimID, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(chbTimBorbe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)))
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnZapamti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 10, Short.MAX_VALUE)
                .addComponent(chbTimBorbe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(chbTimKate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(chbTakmicarskiTim, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivTima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnZapamti)
                .addContainerGap())
        );

        btnIzmeni.setBackground(new java.awt.Color(39, 45, 87));
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("Izmeni");

        btnObrisiTim.setBackground(new java.awt.Color(255, 102, 102));
        btnObrisiTim.setForeground(new java.awt.Color(255, 255, 255));
        btnObrisiTim.setText("Ukloni tim");
        btnObrisiTim.setPreferredSize(new java.awt.Dimension(119, 25));

        btnIzadji.setBackground(new java.awt.Color(39, 45, 87));
        btnIzadji.setForeground(new java.awt.Color(255, 255, 255));
        btnIzadji.setText("Izadji");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPostojeciTim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiTim, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPostojeciTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmeni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzadji)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTimoviItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTimoviItemStateChanged

    }//GEN-LAST:event_cbTimoviItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmTim dialog = new FrmTim(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisiTim;
    private javax.swing.JButton btnZapamti;
    private javax.swing.JButton btnZapamtiIzbor;
    private javax.swing.JComboBox cbTimovi;
    private javax.swing.JCheckBox chbTakmicarskiTim;
    private javax.swing.JCheckBox chbTimBorbe;
    private javax.swing.JCheckBox chbTimKate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelPostojeciTim;
    private javax.swing.JTextField txtNazivTima;
    private javax.swing.JTextField txtTimID;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnZapamti() {
        return btnZapamti;
    }

    public javax.swing.JComboBox getCbTimovi() {
        return cbTimovi;
    }

    public javax.swing.JCheckBox getChbTakmicarskiTim() {
        return chbTakmicarskiTim;
    }

    public javax.swing.JCheckBox getChbTimBorbe() {
        return chbTimBorbe;
    }

    public javax.swing.JCheckBox getChbTimKate() {
        return chbTimKate;
    }

    public javax.swing.JTextField getTxtTimID() {
        return txtTimID;
    }

    public javax.swing.JTextField getTxtNazivTima() {
        return txtNazivTima;
    }

    public JButton getBtnIzadji() {
        return btnIzadji;
    }

    public JButton getBtnZapamtiIzbor() {
        return btnZapamtiIzbor;
    }

    public void addBtnZapamtiListener(ActionListener actionListener) {
        btnZapamti.addActionListener(actionListener);
    }

    public void addZapamtiPostojeciTimListener(ActionListener actionListener) {
        btnZapamtiIzbor.addActionListener(actionListener);
    }

    public void addIzadjiListener(ActionListener actionListener) {
        btnIzadji.addActionListener(actionListener);
    }

    public JPanel getPanelPostojeciTim() {
        return panelPostojeciTim;
    }

    public JButton getBtnIzmeni() {
        return btnIzmeni;
    }

    public void addIzmeniListener(ActionListener actionListener) {
        btnIzmeni.addActionListener(actionListener);
    }

    public JButton getBtnObrisiTim() {
        return btnObrisiTim;
    }

    public void addUkloniTimListener(ActionListener actionListener) {
        btnObrisiTim.addActionListener(actionListener);
    }
 

}
