/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Folio1040
 */
public class FrmTakmicar extends javax.swing.JDialog {

    /**
     * Creates new form FrmTakmicar
     */
    public FrmTakmicar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelTabelaTimova = new javax.swing.JPanel();
        btnIzaberiTim = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTimTakmicara = new javax.swing.JTextField();
        txtTakmicarID = new javax.swing.JTextField();
        cbClanovi = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnDalje = new javax.swing.JButton();
        cbKategorija = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnKreiraj = new javax.swing.JButton();
        panelDalje = new javax.swing.JPanel();
        btnPojedinacno = new javax.swing.JButton();
        btnTimski = new javax.swing.JButton();
        chbPojedinacno = new javax.swing.JCheckBox();
        chbTimski = new javax.swing.JCheckBox();
        lblSlika = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 236, 248));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 34, 89));
        jLabel2.setText("Clan:");

        panelTabelaTimova.setBackground(new java.awt.Color(232, 242, 250));

        btnIzaberiTim.setBackground(new java.awt.Color(135, 180, 215));
        btnIzaberiTim.setForeground(new java.awt.Color(255, 255, 255));
        btnIzaberiTim.setText("Izaberi tim");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 34, 89));
        jLabel4.setText("Tim u kom je clan:");

        txtTimTakmicara.setEnabled(false);

        javax.swing.GroupLayout panelTabelaTimovaLayout = new javax.swing.GroupLayout(panelTabelaTimova);
        panelTabelaTimova.setLayout(panelTabelaTimovaLayout);
        panelTabelaTimovaLayout.setHorizontalGroup(
            panelTabelaTimovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaTimovaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTabelaTimovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabelaTimovaLayout.createSequentialGroup()
                        .addComponent(btnIzaberiTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(270, 270, 270))
                    .addGroup(panelTabelaTimovaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimTakmicara)))
                .addContainerGap())
        );
        panelTabelaTimovaLayout.setVerticalGroup(
            panelTabelaTimovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaTimovaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelTabelaTimovaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTimTakmicara))
                .addGap(18, 18, 18)
                .addComponent(btnIzaberiTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTakmicarID.setEnabled(false);

        cbClanovi.setBackground(new java.awt.Color(232, 242, 250));
        cbClanovi.setForeground(new java.awt.Color(20, 34, 89));
        cbClanovi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 34, 89));
        jLabel1.setText("Takmicar ID:");

        btnDalje.setBackground(new java.awt.Color(135, 180, 215));
        btnDalje.setForeground(new java.awt.Color(255, 255, 255));
        btnDalje.setText("Dalje");

        cbKategorija.setBackground(new java.awt.Color(232, 242, 250));
        cbKategorija.setForeground(new java.awt.Color(20, 34, 89));
        cbKategorija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 34, 89));
        jLabel3.setText("Kategorija:");

        btnKreiraj.setBackground(new java.awt.Color(20, 34, 89));
        btnKreiraj.setForeground(new java.awt.Color(255, 255, 255));
        btnKreiraj.setText("Kreiraj takmicara");

        panelDalje.setBackground(new java.awt.Color(232, 242, 250));

        btnPojedinacno.setBackground(new java.awt.Color(135, 180, 215));
        btnPojedinacno.setForeground(new java.awt.Color(255, 255, 255));
        btnPojedinacno.setText("Pojedinacno takmicenje");

        btnTimski.setBackground(new java.awt.Color(135, 180, 215));
        btnTimski.setForeground(new java.awt.Color(255, 255, 255));
        btnTimski.setText("Takmicenje u timu");

        chbPojedinacno.setBackground(new java.awt.Color(232, 242, 250));
        chbPojedinacno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbPojedinacno.setForeground(new java.awt.Color(20, 34, 89));
        chbPojedinacno.setText("Pojedinacno");
        chbPojedinacno.setEnabled(false);
        chbPojedinacno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPojedinacnoActionPerformed(evt);
            }
        });

        chbTimski.setBackground(new java.awt.Color(232, 242, 250));
        chbTimski.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbTimski.setForeground(new java.awt.Color(20, 34, 89));
        chbTimski.setText("Timski");
        chbTimski.setEnabled(false);
        chbTimski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTimskiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDaljeLayout = new javax.swing.GroupLayout(panelDalje);
        panelDalje.setLayout(panelDaljeLayout);
        panelDaljeLayout.setHorizontalGroup(
            panelDaljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaljeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTimski, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnPojedinacno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaljeLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(chbTimski, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chbPojedinacno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        panelDaljeLayout.setVerticalGroup(
            panelDaljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaljeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDaljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimski, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPojedinacno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelDaljeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbPojedinacno)
                    .addComponent(chbTimski))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDalje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(342, 342, 342))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtTakmicarID)
                        .addGap(264, 264, 264))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addComponent(cbClanovi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cbKategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelTabelaTimova, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDalje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtTakmicarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbClanovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnDalje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDalje, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(panelTabelaTimova, javax.swing.GroupLayout.PREFERRED_SIZE, 99, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addComponent(btnKreiraj)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chbPojedinacnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPojedinacnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbPojedinacnoActionPerformed

    private void chbTimskiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTimskiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbTimskiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTakmicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTakmicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTakmicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTakmicar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmTakmicar dialog = new FrmTakmicar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDalje;
    private javax.swing.JButton btnIzaberiTim;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnPojedinacno;
    private javax.swing.JButton btnTimski;
    private javax.swing.JComboBox cbClanovi;
    private javax.swing.JComboBox cbKategorija;
    private javax.swing.JCheckBox chbPojedinacno;
    private javax.swing.JCheckBox chbTimski;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JPanel panelDalje;
    private javax.swing.JPanel panelTabelaTimova;
    private javax.swing.JTextField txtTakmicarID;
    private javax.swing.JTextField txtTimTakmicara;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnDalje() {
        return btnDalje;
    }

    public JButton getBtnKreiraj() {
        return btnKreiraj;
    }

    public JButton getBtnTimski() {
        return btnTimski;
    }

    public JComboBox getCbClanovi() {
        return cbClanovi;
    }

    public JComboBox getCbKategorija() {
        return cbKategorija;
    }

    public JPanel getPanelDalje() {
        return panelDalje;
    }

    public JPanel getPanelTimova() {
        return panelTabelaTimova;
    }

    public JTextField getTxtTimTakmicara() {
        return txtTimTakmicara;
    }
    
    

    public JTextField getTxtTakmicarID() {
        return txtTakmicarID;
    }

    public JButton getBtnPojedinacno() {
        return btnPojedinacno;
    }

    public JCheckBox getChbPojedinacno() {
        return chbPojedinacno;
    }

    public JCheckBox getChbTimski() {
        return chbTimski;
    }
    

    public void addDaljeListener(ActionListener actionListener) {
        btnDalje.addActionListener(actionListener);
    }

    public void addTimsliListener(ActionListener actionListener) {
        btnTimski.addActionListener(actionListener);
    }

    public void addPojedinacnoListener(ActionListener actionListener) {
        btnPojedinacno.addActionListener(actionListener);
    }

    public void addIzaberiTimListener(ActionListener actionListener) {
        btnIzaberiTim.addActionListener(actionListener);
    }

    public void addKreirajTakmicaraListener(ActionListener actionListener) {
        btnKreiraj.addActionListener(actionListener);
    }

    public JLabel getLblSlika() {
        return lblSlika;
    }


    


}
